### PR TITLE
Update GH Test Matrix with minimum & latest JRuby version

### PR DESCRIPTION
**Pull request by tedhexaflow**

### CODE REVIEW

**Comment by tedhexaflow** [comment]
There seems to be an issue with the bundler version at 'appraisal install' in Github action.

**Comment by bensheldon** [comment]
@tedhexaflow Thanks for opening this! I fixed the bundler issue on `main`. If you rebase this should pass.

I'd like it if this PR bracketed the JRuby versions: have one value in the matrix for the minimum version of JRuby that GoodJob supports, and one value in the matrix for the latest version of JRuby.

**Comment by tedhexaflow** [comment]
@bensheldon Rebased and updated. All checks have passed too.

Please let me know if there's anything else I need to do.

Many Thanks 💚💙💜

**Comment by bensheldon** [comment]
@tedhexaflow Awesome! Please squash this down to a single commit and I'll merge. Thank you!

**Comment by tedhexaflow** [comment]
@bensheldon Sorry about that. Just squashed and pushed. Thanks 💛💚❤️

**Pull request merged**
