### PR TITLE
Spike on data dashboard; pull in full Bootstrap CSS and JS

### PR DESCRIPTION
**Pull request by bensheldon**
Connects to #50 

Screen Shot 2020-09-07 at 2 15 48 PM

### CODE REVIEW

**Comment by bensheldon** [comment]
- [ ] Add `engine` directory to Gemspec

**Comment by morgoth** [comment]
@bensheldon I wanted to try the engine but it doesn't load for me.
I'm using the gem from master branch, but I cannot require "good_job/engine".

I can also see that it is not in load path as stated in https://github.com/bensheldon/good_job/blob/main/good_job.gemspec#L2

```
> pp $LOAD_PATH.grep /good_job/
=> ["/home/wojtek/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/bundler/gems/good_job-c84288185da6/lib"]
```

Do I need to do some extra setup to make it work?

**Comment by bensheldon** [comment]
@morgoth thank you for taking the time to try to get it working. I am investigating.

**Comment by bensheldon** [comment]
@morgoth I have a PR (#134) that I think fixes the problem. Could you try it out locally and give me feedback? Here's some preliminary documentation:

1. Explicitly require the Engine code at the top of your `config/application.rb` file, immediately after Rails is required. This is necessary because the mountable engine is an optional feature of GoodJob.

    ```ruby
    # config/application.rb
    require_relative 'boot'

    require 'rails/all'
    require 'good_job/engine' # <= Add this line
    # ...
    ```

2. Mount the engine in your `config/routes.rb file. The following will mount it at the `example.com/good_job` URL.

    ```ruby
    # config/routes.rb
    # ...
    mount GoodJob::Engine => 'good_job'
    ```

    Because jobs can potentially contain sensitive information, you should have authorization. For example, using Devise's `authenticate` helper, that might look like:

    ```ruby
    # config/routes.rb
    # ...
    authenticate :user, ->(user) { user.admin? } do
      mount GoodJob::Engine => 'good_job'
    end
    ``` 

Thank you 🙏

**Pull request merged**
