### PR TITLE
Keep locale param when submitting dashboard filter

### PR DESCRIPTION
**Pull request by aki77**
Behavior before modification

### CODE REVIEW

**Review by bensheldon — APPROVED** [review]
Thanks for catching that! 🙌🏻 

btw, what are you using to see the DOM changes highlighted in red?

**Comment by bensheldon** [comment]
Released: https://github.com/bensheldon/good_job/releases/tag/v3.4.4

**Comment by aki77** [comment]
Thanks!
The DOM highlighting is due to the following changes.
2b584df6941cbe4ad6231ec09f33236c3e8d63fa

Whenever good_job is used from a language other than the one provided by default, it is always highlighted.
If highlighting is for good_job developers, I think it would be better if only developers explicitly enable highlighting.

**Comment by bensheldon** [comment]
@aki77 oh 🤦🏻 I had forgotten that's GoodJob code. Yes, that highlight should be removed; the intent was to help with internationalizing GoodJob, but I wasn't thinking about the side effects.

I'll remove it.

**Pull request merged**
