### PR TITLE
Recreate cron indexes to be conditional

### LINKED ISSUE #1161: Use partial indices for cron_key?
Hi @bensheldon

I observed constantly growing indices:

```
'good_jobs::index_good_jobs_on_cron_key_and_created_at' bloat 35372.5 waste 553 MB
'good_jobs::index_good_jobs_on_cron_key_and_cron_at' bloat 33274.0 waste 520 MB
```

The problem is that the application **does not use the CRON functionality** - thus cron_key and cron_at are always NULL.

Application uses PG version 14.7, good_jobs table has a lot of churn, but except occasional bursts - enqueued jobs count is low (< 100). VACUUMS are triggered regularly, but for some reason those indices' size stay intact. Non-production databases (staging/sandbox) manifest themselves in the same way.

I wonder if other users have also experienced this problem?

Problem can be mitigated with `VACUUM FULL good_jobs` or `REINDEX ...`, but I think the correct solution is to use partial indices:

```rb
add_index :good_jobs, [:cron_key, :created_at], name: :index_good_jobs_on_cron_key_and_created_at, where: 'cron_key IS NOT NULL'
add_index :good_jobs, [:cron_key, :cron_at], name: :index_good_jobs_on_cron_key_and_cron_at, where: 'cron_key IS NOT NULL', unique: true
```

Is there any downside to this approach? If not, I'll be happy to prepare a PR to fix it.

### PR DESCRIPTION
**Pull request by defkode**
fixes #1161

### CODE REVIEW

**Comment by bensheldon** [comment]
@defkode sorry, I realized I have so much experience doing this :D 

- I think this can be a single migration.
- Indexes are a little weird to do idempotently because each call needs to be wrapped with an `if index_exists?` check because the migration could fail out somewhere in the middle.
- You'll also need to update the `templates/install` migration
- Then you'll need to run the template generator on the demo app to generate the live database migration files. Then run _those_ which will update the demo app's schema.rb

...so ultimately this should be updates to 4 files:

- lib/generators/good_job/templates/update/migrations/06_recreate_good_job_cron_indexes.rb
- lib/generators/good_job/templates/install/migrations/06_recreate_good_job_cron_indexes.rb
- demo/db/migrate/xxxxx_recreate_good_job_cron_indexes.rb
- demo/db/schema.rb

**Comment by defkode** [comment]
@bensheldon Thanks for hints. PR is updated.

**Comment by bensheldon** [comment]
@defkode thank you! I just made a few tweaks. I'm going to let CI run through 💚 and then it should be done ⭐

**Comment by bensheldon** [comment]
I'm pretty certain this is failing because of a change introduced today on Rails main: https://github.com/rails/rails/pull/50205#issuecomment-1835416318

**Pull request merged**
