### PR TITLE
This is a naive implementation of an idle timeout.

### PR DESCRIPTION
**Pull request by netikular**
I've still got to clean up some formatting to put it back the way that it was - I'll update this PR when I get that done.

I've added a `--count-till-idle` command line argument that is the number of seconds a good_job process will stick around.  This is based on the fact that the main loop sleeps for a tenth of a second and the code checks for working threads each time through the loop, if it finds working threads it resets the idle time out.

This is a rough implementation, I've not extended any tests to check for this yet.  But wanted to push up the PR to further the conversation.

I'm currently running this change in production and is working as I expect.

- [x] Return formatting to original

Connects to #1140

### CODE REVIEW

**Comment by bensheldon** [comment]
@netikular thanks for doing this! 🙇🏻 

What's the best way to make changes here? I normally would simply push up to your branch, but I don't want to break anything if you're running this particular branch in production.

(I could also leave a bunch of comments on the PR, but I tend to feel like the effort between trying to be specific about the change I want, and just making it and then explaining why after the fact is a better tradeoff).

**Comment by bensheldon** [comment]
In terms of the things i'm thinking of:

- I'd like to track the true "last_job_executed_at" time. That will involve adding that to `GoodJob::Metric` (which is instantiated in a scheduler) and then exposing that through stats.
- Schedulers can also be MultiSchedulers, so the stats needs to be aggregated in a MultiScheduler too (I might even refactor some of that so it's _always_ a multischeduler rather than right now it's only sometimes).
- Rather than exposing all of stats from the capsule, I'd rather more narrowly expose two values: "active_execution_threads_count" and "last_job_executed_at"; I like to keep interfaces as specific as possible (`stats` is not a good example of that)
- I'd like the name to be `--shutdown-on-idle SECONDS`, with matching name in Configuration
- This makes me think that there needs to be a like `Capsule.started?(wait:)` option so that we make sure that the capsule is fully started before counting down (we can probably defer that for now, but I do imagine the lack of that will cause me some support grief at some point).

**Comment by netikular** [comment]
@bensheldon Sorry for the delay. Had to step away from the computer for a few days.

Feel free to make any changes, I'll make the changes that you've recommended in your comment and push them up this morning.

**Comment by netikular** [comment]
Instead of pushing the logic of idle all the way up to the CLI I thought
it would be better in the GoodJob::Capsule class.

I've created a `#idle?` method that does this check based on the last
time a scheduler in the GoodJob::Capsule has run a job.

I ran into an interesting thing that if I check the configuration object
in the initialization of the GoodJob::Capsule it causes a crash because
rails is not initialized yet.  The configuation object can't access the
rails config.

I instead changed it so that in the initialize of the GoodJob::Capsule
the `shutdown_on_idle_enabled` flag is set to false - meaning never
shutdown on idle. Then in `#start` the GoodJob::Capsule checks the
config and sets the flag so that #idle? method will work.

**Comment by netikular** [comment]
@bensheldon the last PR that I put in should make this good to go.

Looking forward to your thoughts.

**Comment by bensheldon** [comment]
@netikular thank you! I'm at RubyConf this week so I'll be a little slow in getting to this. But I really appreciate it!

**Comment by netikular** [comment]
@bensheldon have fun at ruby conf.  I've not been in years!

**Comment by bensheldon** [comment]
I wasn't able to push up to your branch (I think that's because it's the `main` branch), so I made a new PR: #1159

**Pull request closed without merging**
