### PR TITLE
Re-add footer with GoodJob version number

### LINKED ISSUE #1183: Show last update on top nav bar
Based on this [discussion](https://github.com/bensheldon/good_job/discussions/1109), it was suggested by @simi as an initial idea moving the footer message to the top.
image
About been not sure what to include in footer, I think should be useful author name(with link to author) and github(with link to goodjob repository).
image

### PR DESCRIPTION
**Pull request by Pauloparakleto**
close #1183 
Based on this [discussion](https://github.com/bensheldon/good_job/discussions/1109), it was suggested by @simi as an initial idea moving the footer message to the top.
image
@bensheldon  About been not sure what to include in footer, I think should be useful author name(with link to author) and github(with link to goodjob repository).
image

### CODE REVIEW

**Comment by simi** [comment]
I think footer can be removed at all then to release some space.

**Comment by Pauloparakleto** [comment]
Was this merge intentional? @bensheldon ? I can rebase into new main and then push again mine to yours. The idea behind changing the translation files keys it to keep the context updated. Please, let me know what to do next. Happy new year!

**Comment by bensheldon** [comment]
@Pauloparakleto yep, sorry. I realized there was a duplicate feature in #1204, but I liked your retaining of the footer so I wanted to preserve that.

**Comment by Pauloparakleto** [comment]
> @Pauloparakleto yep, sorry. I realized there was a duplicate feature in #1204, but I liked your retaining of the footer so I wanted to preserve that.

Thanks again, I have used this project a lot in my open source project. Contributing to yours has been part of my new job.

**Comment by bensheldon** [comment]
> Thanks again, I have used this project a lot in my open source project. Contributing to yours has been part of my new job.

Yay! I love to hear that. I'm really glad that GoodJob has been of service! Also I really appreciate the contributions 🙇🏻

**Pull request merged**
