### PR TITLE
Update Dashboard to Bootstrap 5

### PR DESCRIPTION
**Pull request by morgoth**
Looks like for current functionality, there is no need for js at all.
It can be added when such need will arrive.

Closes https://github.com/bensheldon/good_job/issues/258

### CODE REVIEW

**Comment by bensheldon** [comment]
@morgoth I fixed the Gemfile issue on the main branch (#261). If you rebase against main I think this will pass.

**Comment by morgoth** [comment]
@bensheldon it helped. Thanks

**Review by bensheldon — APPROVED** [review]
👍 thank you!

**Comment by bensheldon** [comment]
@morgoth this is released in `v1.9.5`

**Pull request merged**
