### PR TITLE
Remove usage of COALESCE from dashboard chart

### PR DESCRIPTION
**Pull request by bananatron**
- Fixes https://github.com/bensheldon/good_job/issues/1305 which may actually be a non-issue.
- The verbosity may not be worth the advantage given the reproducibility of this issue.

### CODE REVIEW

**Comment by bensheldon** [comment]
This is lovely! Any chance you could try putting the entire COALESCE into Arel?

**Comment by bananatron** [comment]
@bensheldon I almost never use Arel so lmk if this is better/worse.

**Comment by bensheldon** [comment]
Sorry, I missed entirely that the Arel was then getting `to_sql`'ed into a larger block of text 🤦🏻 

I'm still unsure of why those spaces got inserted into the SQL previously. I'll accept this and maybe someday it will be fully Arel-ized.

**Comment by bananatron** [comment]
@bensheldon I am also unsure :[ but my theory is some weird level rails dependency issue 🤷

**Comment by bananatron** [comment]
This is coming back with a bundler update, I wonder if the ruby version is somehow involved 🤔 

`ActiveRecord::StatementInvalid in GoodJob::Jobs#index` This prevents me from viewing my jobs page.

```Showing /Users/_/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/good_job-3.28.2/app/views/good_job/jobs/index.html.erb where line #2 raised:

PG::SyntaxError: ERROR:  syntax error at or near ":"
LINE 1: ... ( good_jobs.scheduled_at ,good_jobs.created_at ) : : TIMEST...
```

**Pull request merged**
