### PR TITLE
update Gemfile.lock to latest dependencies

### PR DESCRIPTION
**Pull request by jrochkind**
Via running `bundle update` and committing results.

Some would advise not having Gemfile.lock checked into repo for gem source in the first place. Eg https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/  https://github.com/radar/guides/issues/14

But if you are going to have it checked in, it's probably good to periodically update it so dev and test environments are against latest dependency releases that meet requirements.

### CODE REVIEW

**Comment by jrochkind** [comment]
Interesting! Doesn't pass on jruby after updating all gems -- to versions that an app using good_job may very well be using! This PR does not change any gemspec requirements. 

This means good_job may actually have trouble running with latest dependency releases on jruby? 

(Assuming main branch would currently pass on jruby for sure?)

`NameError: uninitialized constant Gem::Requirement` -- that's weird!

**Comment by bensheldon** [comment]
Thank you @jrochkind. I prefer to check-in the Gemfile.lock because it makes it easier to reproduce gem development issues across machines. I've also been burned in the past coming to a project and finding that it no longer successfully builds and not knowing with what dependencies it would build. I also think there are several overlapping concerns that are unfortunately covered by the same Gemfile/gemspec tooling:

- Gem Development, which has hard development dependencies that are unrelated to the packaged gem (e.g. RSpec, Rubocop, various, etc.).
- Gem Operations, which also has hard dependencies, such as tooling for automating build steps, authoring changelogs, gem packaging, etc.
- Gem QA, which I agree should not be version locked. The appraisal-based Gemfiles, which are used in the CI test matrix, do not check-in their `Gemfile.lock` files, for the reason you described.

It looks like some Rubocop cops got updated. Do you want to update those? 

Also, I am now seeing the `faraday-retry` message. In poking at it, I was running into unresolvable dependency problems, so if you're ok ignoring that for now, I don't think it has any impact (that dependency is for `github_changelog_generator` which is only used when publishing new versions of the gem; it's unfortunate that the warning happens everywhere)

**Comment by jrochkind** [comment]
I mean, i would not love getting that rspec-retry warning every time my app boots! But I guess there's worse things. 

The error I see in the jruby failure that cancelled the build does not seem rubocop-related?

Honestly, I was just trying to help by updating the Gemfile.lock, and hoping it would just pass or have obvious easy to fix problems!  I may not have a lot of time to debug what went wrong, if you aren't interested in doing so either right now, feel free to close this PR!

**Comment by bensheldon** [comment]
> i would not love getting that rspec-retry warning every time my app boots!

@jrochkind sorry I maybe misunderstood what you're experiencing. You're seeing that warning in your Rails application that is using the packaged GoodJob gem? That's unexpected to me because faraday is a dependency of the Gemspec's `gem_development_dependency`, which I don't think should be installed as a consumer of the gem (only when directly developing the gem itself).

**Comment by jrochkind** [comment]
Oh ok no i'm not I was just worried I would. Come to think of it, my app has faraday-retry already anyway as it happens. No worries.

**Pull request merged**
