### PR TITLE
Update GH Test Matrix with latest JRuby 9.2.19.0

### PR DESCRIPTION
**Pull request by tedhexaflow**

### CODE REVIEW

**Comment by tedhexaflow** [comment]
Hello @bensheldon,
Checks are failing and It seems there is a 'PostgresNoticeError:' error.
I believe it is not related to the JRuby version.
Could you kindly check? 

Thanks 🙏

**Comment by bensheldon** [comment]
@tedhexaflow thank you! I'll get the tests passing; it's unrelated. I've been chasing down a flakey test all week 😢

**Comment by bensheldon** [comment]
@tedhexaflow please rebase against `main`; I have those test flakes fixed (I hope!).

**Comment by bensheldon** [comment]
@tedhexaflow Thank you! 🥇

**Pull request merged**
