### PR TITLE
GoodJob.cleanup_preserved_jobs: add :include_discarded option

### PR DESCRIPTION
**Pull request by jonleighton**
This change allows the caller of `GoodJob.cleanup_preserved_jobs` to specify the `:include_discarded` option, rather than always relying on the value that is set in the configuration.

This would enable us to e.g. set `config.cleanup_preserved_jobs_before_seconds_ago` to a very low value (e.g. 10 seconds), but also set `config.cleanup_discarded_jobs = false` so that we can retain discarded jobs for longer in case we want to inspect them or manually retry then.

We would then set up a separate maintenance job to call `GoodJob.cleanup_preserved_jobs(older_than: some_longer_period, include_discarded: true)`.

### CODE REVIEW

**Comment by jonleighton** [comment]
Note that it was proving difficult to get the tests running in my local dev environment, so I hoped to push this up and run it on your CI.

**Comment by jonleighton** [comment]
I realised that this project is setup for devcontainers and managed to run and fix the tests locally, so hopefully CI will pass now.

**Comment by jonleighton** [comment]
Looks like the `rails_head` one failed CI, but that looks unrelated to my change.

**Comment by bensheldon** [comment]
This looks good 👍🏻 

I have this vague memory of not wanting to pass through the value as an argument because I was worried that someone might manually delete jobs and cause operational confusion... but I think your reasoning for why it would be useful is compelling.

**Comment by jonleighton** [comment]
Thank you!

**Pull request merged**
