### PR TITLE
FreeBSD startup script

### LINKED ISSUE #214: Goodjob startup script for FreeBSD
I am working on a startup script for goodjob working for FreeBSD

But maybe someone already has created this, without sharing?

It must follow the guidelines described here: 
https://docs.freebsd.org/en_US.ISO8859-1/books/handbook/configtuning-starting-services.html

But would it be included in this project, if I add a pull request?

### PR DESCRIPTION
**Pull request by lauer**
Fixes #214

The script is tested and works on 

* FreeBSD 12 installation with Ruby 2.7.2 installed with pkg.
* FreeBSD 12 installation with Ruby 2.7.2 installed with rbenv

### CODE REVIEW

**Comment by lauer** [comment]
Btw, I was heavy inspired by this GIST for Gitlab FreeBSD startup
https://gist.github.com/denvazh/5588936

**Review by bensheldon — COMMENTED** [review]
@lauer This is great! Could you please move it into an `/examples` directory. I don't believe that this should be included in the gem package (anything in `/lib` is packaged).

**Comment by lauer** [comment]
Why wouldn't you have it included in the gem? It makes it easier to write documentation or helper scripts for installing the startup script?

Would you then add some text to Readme with how to fetch the startup script from raw.github.com?

**Comment by bensheldon** [comment]
@lauer I was imagining that someone would be copy-pasting the file from Github via the readme/docs, making some modifications for their local needs, and then dropping the file into `rc.d/`.

I would like to keep the gem package itself limited to just universally-applicable Ruby code to keep the install size as small as possible.

You're correct though that this should be referenced from the Readme or else it's likely not to be discovered.

Alternatively, do you think putting this code in the Wiki would make it more discoverable/modifiable/explanatory? I will likely have to caveat most infra questions with "I can provide limited support, ymmv."

**Comment by lauer** [comment]
I have now moved the init script to examples directory.

I don't know if it was correct to merge your main branch into this. I am used to gerrit where you always works with patch set, and have to rebase into main branch.

**Comment by bensheldon** [comment]
@lauer are you able to rebase/squash this down to a single commit so that it doesn't have the merge commit?

**Comment by lauer** [comment]
@bensheldon but isn't that something you can choose when accepting the PR? 
https://github.blog/2016-04-01-squash-your-commits/

**Comment by bensheldon** [comment]
@lauer I can squash it via GH, but the resulting commit can possibly remove your authorship so you don't show up implicitly as a contributor:

https://github.com/isaacs/github/issues/1303

Let me know if you want me to do the squishing.

**Comment by lauer** [comment]
@bensheldon okay, it's not really a big deal for me, but how can I rebase/squash this to a single commit?

**Comment by bensheldon** [comment]
@lauer I did more reading and it seems like because the commits are only authored by you, the squash-and-merge command will have the correct author information. I'll give that a shot and save you the trouble.

For the future, to squash it on your own, when this branch is checked out, run `git rebase --interactive origin/main` 

That'll pop up an EDITOR interface that looks like this:

```bash
pick 8053406 FreeBSD startup script
pick 580c245 Moved init script into examples to avoid being a part of the gem

# Rebase df68860..580c245 onto df68860 (2 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
```

And then replace `pick` with `fixup` for the commits to merge into the previous commit:

```bash
pick 8053406 FreeBSD startup script
fixup 580c245 Moved init script into examples to avoid being a part of the gem
```

**Pull request merged**
